weather_app_site/register/urls.py
from django.conf.urls import url
from . import views

app_name = 'register'
urlpatterns = [ url( r"^$", views.index, name="index" ),
                url( r"^confirmation/$", views.confirmation, name="confirmation" ),
              ]

weather_app_site/weather_app_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [ url( r"^register/", include("register.urls") ),
                url( r"^admin/", admin.site.urls ),
              ]

weather_app_site/register/models.py
from __future__ import unicode_literals
from django.db import models
from .global_vars import US_CITY_MAX_LEN, US_STATE_MAX_LEN, AIRPORT_MAX_LEN, EMAIL_MAX_LEN

# Create your models here.
class Location( models.Model ):
    """
       Currently, longest U.S. city name is 22 characters. 
       Add extra space for names of future cities.
       There are currently 19,354 incorporated places in the U.S.
    """
    us_city = models.CharField( max_length=US_CITY_MAX_LEN )
    """
        2 character abbreviation for U.S. state.
        There are currently 50 U.S. states.
    """
    us_state = models.CharField( max_length=US_STATE_MAX_LEN )
    # U.S. city population. Do not allow negative values.
    population = models.PositiveIntegerField( default=0 )
    """
        3 character airport code for airport located closest in 
        proximity to a given city and state.
    """
    airport = models.CharField( max_length=AIRPORT_MAX_LEN )
    def __str__( self ):
        # Adjust the string representation of the model for the drop down menu.
        return self.us_city + ", " + self.us_state

class Address( models.Model ):
    # Relate each address to a location
    location = models.ForeignKey( Location, on_delete=models.CASCADE )
    """
       E-mail address. Maximum length is 254.
       EmailField uses EmailValidator to validate the input.
       Ensure that only one no duplicate e-mail addresses are entered.
    """
    email_address = models.EmailField( max_length=EMAIL_MAX_LEN, unique=True )
    # Creation date for the e-mail address
    creation_date = models.DateTimeField( "Creation Date" )

# class weather_image( models.Model ):
    # Image associated with each type of weather condition.
#    weather_image = ImageField()

weather_app_site/register/forms.py
from django import forms
from django.utils.encoding import force_text
from django.utils.safestring import mark_safe
from django.utils.html import format_html
from .models import Address, Location
from .global_vars import NUM_CITIES, DEFAULT_OPTION

class Default_opt_disabled_widget( forms.Select ):

    def render_option(self, selected_choices, option_value, option_label):
        if option_value is None:
            option_value = ''
        option_value = force_text(option_value)
        if option_value in selected_choices:
            selected_html = mark_safe(' selected="selected"')
            if not self.allow_multiple_selected:
                # Only allow for a single selection.
                selected_choices.remove(option_value)
        else:
            selected_html = ''
        option_label = option_label.replace( ':', '' )
        if option_value == DEFAULT_OPTION:
            return format_html('<option value="{}"{} selected="selected" disabled>{}</option>', 
                               option_value, selected_html, force_text(option_label))
        else:
            return format_html('<option value="{}"{}>{}</option>', option_value, selected_html, force_text(option_label))

class RegisterForm( forms.Form ):
    # Add the email form.
    email_address = forms.EmailField( label="Email Address", 
                                      required=True 
                                    )
    # Pull the top NUM_CITIES cities by population.    
    top_pop_cities = Location.objects.order_by('-population')[:NUM_CITIES]
    # Add the city drop down box.
    choices = []
    choices.append( (DEFAULT_OPTION, DEFAULT_OPTION) )
    for next_city in top_pop_cities:
        choices.append( (next_city.id, str(next_city)) )
    location_id = forms.ChoiceField( label="Location", 
                                     choices=choices, 
                                     widget=Default_opt_disabled_widget,
                                     required=True 
                                   )

    def clean( self ):
        """
            Include an error message when an email address has already
            been registered
        """
        cleaned_data = super( RegisterForm, self ).clean()
        email_address = cleaned_data.get( 'email_address' )
        location_id = cleaned_data.get( 'location_id' )
        addresses = Address.objects.all()
        for address in addresses:
            if email_address == address.email_address:
                self.add_error( 'email_address', 'Email address has already registered' )

weather_app_site/register/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.core.exceptions import ValidationError
from .models import Address, Location
from .global_vars import NUM_CITIES, TITLE
from .forms import RegisterForm

# Create your views here.
def index( request ):
    template = 'register/index.html'
    redirect = "confirmation/" 
    error_msg = ""
    if request.method == "POST":
        # Validate the contents of the form and update the database.
        form = RegisterForm( request.POST )
        if form.is_valid():
            email_address = form.cleaned_data['email_address']
            location_id = form.cleaned_data['location_id']
            try:
                fk = Location.objects.all().filter( pk=location_id )
                if len(fk) != 1:
                    # Primary key should always be unique.
                    raise ValidationError( "Invalid primary key supplied" )
                a = Address( location=fk[0], email_address=email_address, creation_date=timezone.now() )
                # Validate e-mail once more before saving.
                a.full_clean()
                a.save()
                # Successfully entered e-mail address. Redirect to confirmation page.
                return HttpResponseRedirect( redirect )
            except ValidationError, exc:
                # Capture any unexpected error messages.
                error_msg = "%s" % exc
        else:
             error_msg = "Invalid form"
    else:
        # First time navigating to the page. Create an empty form.
        form = RegisterForm( initial={'Where do you live?': '0'} )
    context = { 'title': TITLE,
                'form': form,
                'error_msg': error_msg
              }
    return render( request, template, context )

def confirmation( request ):
    template = 'register/confirmation.html'
    result = "Successfully registered e-mail address!"
    context = { 'title': TITLE,
                'result': result,
              }
    return render( request, template, context )

weather_app_site/register/templates/register/confirmation.html
<!DOCTYPE html>
<html>
 <head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
  <title>{{ title }}</title>
 </head>
 <body>
  <div>
   <h2>{{ title }}</h2>
   <hr />
   <br />
  </div>
  <div>
   <p class="result">{{ result }}</p>
  </div>
  <br />
  <br />
  <br />
 </body>
</html>

weather_app_site/register/templates/register/index.html
<!DOCTYPE html>
<html>
 <head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
  <title>{{ title }}</title>
 </head>
 <body>
  <div>
   <h2>{{ title }}</h2>
   <hr />
   <br />
  </div>
  {% if error_msg %}
   <div>
    <h3>{{ error_msg }}</h3>
   </div>
  {% endif %}
  <div>
   <form action="{% url 'register:index' %}" method="post">
    <!--Prevent cross site request forgeries-->
    {% csrf_token %}
    {{ form.as_p }}
    <br />
    <input id="submit_button" type="submit" value="Subscribe" />
   </form>
  </div>
  <br />
  <br />
  <br />
 </body>
</html>

weather_app_site/register/templates/register/index_backup.html
<!DOCTYPE html>
<html>
 <head>
  <title>{{ title }}</title>
 </head>
 <body>
  <div>
   <h2>{{ title }}</h2>
  </div>
<!--  {% if top_pop_cities %} -->
   <div>
    <form action="{% url 'register:confirmation' %}" method="post">
     <!--Prevent cross site request forgeries-->
     {% csrf_token %}
     <!--
     E-mail Address
     <br />
     <input type="text" name="email_address" value="test@sample.com" />
     <br />
     <select name="next_city_pk">
      Location
      <br />
      {% for next_city in top_pop_cities %}
       <option value="{{ next_city.id }}">{{ next_city }}</option>
      {% endfor %}
     </select>
     <input type="submit" value="Submit" />
     -->
     {{ form }}
    </form>
   </div>
<!--  {% else %}
   <div>
    <p>No cities have been entered into the database.</p>
   </div>
  {% endif %}
-->
 </body>
</html>